# general conf
image_size: 1000
percentage_train: 0.8
max_elements: 9600
period_to_save_cp: 5
num_epochs_for_lin_regression: 40
tot_num_epochs: 400
batch_size: 40
lr: 0.001
train_loss_type: MAE  # CE, MSE or MAE
val_loss_type: MAE # same choice, but should be kept constant (MSE) for all configs
rot_range: 0
use_fft: True

# model conf
residual: False
num_convs_per_block: 4
num_blocks_per_res: 1
downsample_factor: 2
use_max_pool: False
downsample_with_first_conv: True
num_dense_layers: 1
latent_features: 64
kernel: 3
features: 8
max_features: 32
norm_type: batch  # batch, pixel or None (couldn't find instance norm)
min_res: 4
lrelu_alpha: 0.2
use_bias: False
dropout: 0.3
weight_reg_kind: l2
weight_reg_factor: 0