# general conf
image_size: 1000
percentage_train: 0.8
max_elements: 1600
period_to_save_cp: 10
tot_num_epochs: 40
batch_size: 20
lr: 0.001
loss_type: MSE  # BCE or MSE
model_kind: Till
use_bias: False

# Till model conf
till:
  kernel: 3
  features: 32
  max_features: 256
  norm_type: batch
  min_res: 4