# general conf
image_size: 125
percentage_train: 0.8
max_elements: 9600
period_to_save_cp: 5
num_epochs_for_lin_regression: 20
tot_num_epochs: 40
batch_size: 20
lr: 0.001
train_loss_type: MAE  # CE, MSE or MAE
val_loss_type: MSE # same choice, but should be kept constant (MSE) for all configs
use_bias: False

# Till model conf
till:
  kernel: 3
  features: 8
  max_features: 64
  norm_type: batch
  min_res: 4