histogram_type : ROI
split_ratio: 0.5
num_imgs_to_load: 2700
n_estimators:
  - 7
  - 14
  - 70
  - 130
ranges:
      -
        - 10
        - 90
      -
        - -120
        - 180

# specify histograms to include
ROI_options:
  whole_img:
    include: True
    prepr_fft: True
    num_bins:
            - 33
            - 15

  quarter_img:
    include: False
    prepr_fft: True
    num_bins: 30

  radial:
    include: True
    prepr_fft: True
    shift_fft: True
    num_bins:
            #- 30
            #- 60
            -
              - 33
              - 15
    radii:
         # - 245
         #- - 150
         #  - 300
         - -460

  grad:
    include: True
    prepr_fft: True
    num_bins: 9

  angle:
    include: False
    prepr_fft: True
    num_bins:
             - 30

    angle_l:
           - 0

    angle_h:
           - 30
