histogram_type : ROI
split_ratio: 0.9
num_imgs_to_load: 1500

# specify histograms to include
ROI_options:
  whole_img:
    include: True
    prepr_fft: True
    num_bins: 90

  quarter_img:
    include: False
    prepr_fft: True
    num_bins: 30

  radial:
    include: True
    prepr_fft: True
    shift_fft: False
    num_bins:
            #- 30
            #- 60
            - 30
    radii:
         - 245
         #- - 150
         #  - 300
         #- -453

  grad:
    include: False
    prepr_fft: True
    num_bins: 36

  angle:
    include: False
    prepr_fft: True
    num_bins:
             - 30

    angle_l:
           - 0

    angle_h:
           - 30
