# general conf
image_size: 1000
percentage_train: 0.8
max_elements: 9600
period_to_save_cp: 5
epochs_per_data_load: 1
num_epochs_for_lin_regression: 10
tot_num_epochs: 40
batch_size: 20
lr: 0.01
loss_type: MSE  # BCE or MSE
model_kind: Till
use_bias: False

# Till model conf
till:
  kernel: 3
  features: 8
  max_features: 64
  norm_type: batch
  min_res: 4