# general conf
image_size: 28
image_channels: 1
vmin: -1
vmax: 1  # use either -1 and 1 or 0 and 1
percentage_train: 0.9  # validation doesn't work with star patches yet
#val_model_kind: rf  # nn for neural network or rf for random forest
period_to_save_cp: 40
period_for_val: 5
num_epochs: 400
batch_size: 200
lr: 0.0001
lr_decay: 0.00  # experiment
gan_loss: lsgan
nn_val_model_path: reference_run/fft_4convs_8features_MAE/cp-0140.ckpt
rf_val_model_path: final_model/random_forest_96_1.pkl
num_val_images: 100
conditional: True

# general model conf

model_kind: 4
num_convs_per_res: 1
kernel: 5  # 5 in tf DCGAN
features: 4
max_features: 128  # 128 in tf DCGAN
norm_type: batch
min_res: 4
lrelu_alpha: 0.2
weight_reg_kind: l2
weight_reg_factor: 0
ratio_gen_dis: 1  # 1 in tf DCGAN
# special generator and discriminator conf
dis:
  strided_conv: True  # True in tf DCGAN
  num_dense_layers: 2
  dropout: 0.3  # 0.3 in tf DCGAN
  use_bias: True  # True in tf DCGAN

gen:
  transp_conv: False  # True in tf DCGAN
  use_bias: False  # False in tf DCGAN
  input_neurons: 100  # 100 in tf DCGAN
