# general conf
image_size: 125
percentage_train: 0.9
max_elements: 9600
period_to_save_cp: 5
num_epochs_for_lin_regression: 20
num_epochs: 400
batch_size: 20
lr: 0.001
train_loss_type: MSE  # CE, MSE or MAE
val_loss_type: MSE # same choice, but should be kept constant (MSE) for all configs
gan_loss: lsgan
rot_range: 0

# general model conf

num_convs_per_res: 3

kernel: 3
features: 4
max_features: 32
norm_type: batch
min_res: 4
lrelu_alpha: 0.2
use_bias: False
weight_reg_kind: l2
weight_reg_factor: 0
# special generator and discriminator conf
dis:
  strided_conv: True
  num_dense_layers: 2
  dropout: 0.3

gen:
  transp_conv: False