# general conf
image_size: 28
image_channels: 1
vmin: -1
vmax: 1  # use either -1 and 1 or 0 and 1
percentage_train: 1  # validation doesn't work with star patches yet
period_to_save_cp: 5
num_epochs: 400
batch_size: 100
lr: 0.0001
lr_decay: 1/200  # experiment
gan_loss: Default
val_model_cp: 3convs/cp-0137.ckpt
jitter_padding: 2  # randomly translate input batch by padding black pixels. Use multiple of 2.

# general model conf

model_kind: 3
num_convs_per_res: 1
kernel: 5  # 5 in tf DCGAN
features: 4
max_features: 64  # 128 in tf DCGAN
norm_type: batch
min_res: 4
lrelu_alpha: 0.2
weight_reg_kind: l2
weight_reg_factor: 0
ratio_gen_dis: 3  # 1 in tf DCGAN
# special generator and discriminator conf
dis:
  strided_conv: True  # True in tf DCGAN
  num_dense_layers: 2
  dropout: 0.3  # 0.3 in tf DCGAN
  use_bias: True  # True in tf DCGAN

gen:
  transp_conv: False  # True in tf DCGAN
  use_bias: False  # False in tf DCGAN
  input_neurons: 100  # 100 in tf DCGAN