# general conf
image_size: 125
image_channels: 1
vmin: 0
vmax: 1
percentage_train: 0.9
max_elements: 9600
period_to_save_cp: 5
num_epochs_for_lin_regression: 20
num_epochs: 400
batch_size: 25
lr: 0.0001
train_loss_type: MSE  # CE, MSE or MAE
val_loss_type: MSE # same choice, but should be kept constant (MSE) for all configs
gan_loss: Default
rot_range: 0

# general model conf

model_kind: 1
num_convs_per_res: 1
kernel: 5
features: 4
max_features: 32
norm_type: batch
min_res: 4
lrelu_alpha: 0.2
weight_reg_kind: l2
weight_reg_factor: 0
ratio_gen_dis: 1
# special generator and discriminator conf
dis:
  strided_conv: True
  num_dense_layers: 2
  dropout: 0.3
  use_bias: False

gen:
  transp_conv: False
  use_bias: False
  input_neurons: 100